### ISSUE TITLE
Invalid Syntax on OSX

### ISSUE THREAD

**Issue by tobiasgrosser** [xdslproject/xdsl#2091]
I get the following error when running xdsl-opt on OSX:

```
tobiasgrosser@Tobiass-MacBook-Pro-4 tripos2 % pip3 install xdsl
Defaulting to user installation because normal site-packages is not writeable
Collecting xdsl
  Downloading xdsl-0.15.0-py3-none-any.whl (376 kB)
     |████████████████████████████████| 376 kB 6.2 MB/s 
Requirement already satisfied: pip<24.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from xdsl) (21.2.4)
Collecting typing-extensions<5,>=4.7
  Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting ordered-set==4.1.0
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting immutabledict<3.0.1
  Downloading immutabledict-3.0.0-py3-none-any.whl (4.0 kB)
Installing collected packages: typing-extensions, ordered-set, immutabledict, xdsl
  WARNING: The scripts irdl-to-pyrdl, xdsl-opt and xdsl-run are installed in '/Users/tobiasgrosser/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed immutabledict-3.0.0 ordered-set-4.1.0 typing-extensions-4.9.0 xdsl-0.15.0
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
tobiasgrosser@Tobiass-MacBook-Pro-4 tripos2 % ls
2024-p04-q05-solutions.aux	2024-p04-q05.pdf		2024-p04-q06.aux		2024-p08-q09-solutions.log	2024-p08-q09.tex		make-questions.bat
2024-p04-q05-solutions.log	2024-p04-q05.tex		2024-p04-q06.log		2024-p08-q09-solutions.pdf	Makefile			tripos-config.tex
2024-p04-q05-solutions.pdf	2024-p04-q06-solutions.aux	2024-p04-q06.pdf		2024-p08-q09.aux		Makefile-dependencies		tripos.cls
2024-p04-q05.aux		2024-p04-q06-solutions.log	2024-p04-q06.tex		2024-p08-q09.log		make-clean.bat
2024-p04-q05.log		2024-p04-q06-solutions.pdf	2024-p08-q09-solutions.aux	2024-p08-q09.pdf		make-papers.bat
tobiasgrosser@Tobiass-MacBook-Pro-4 tripos2 % /Users/tobiasgrosser/Library/Python/3.9/bin/xdsl-opt 
Traceback (most recent call last):
  File "/Users/tobiasgrosser/Library/Python/3.9/bin/xdsl-opt", line 5, in <module>
    from xdsl.tools.xdsl_opt import main
  File "/Users/tobiasgrosser/Library/Python/3.9/lib/python/site-packages/xdsl/tools/xdsl_opt.py", line 1, in <module>
    from xdsl.xdsl_opt_main import xDSLOptMain
  File "/Users/tobiasgrosser/Library/Python/3.9/lib/python/site-packages/xdsl/xdsl_opt_main.py", line 7, in <module>
    from xdsl.dialects.builtin import ModuleOp
  File "/Users/tobiasgrosser/Library/Python/3.9/lib/python/site-packages/xdsl/dialects/builtin.py", line 401
    match self.type.signedness.data:
          ^
SyntaxError: invalid syntax
```

**Comment by superlopuh** [comment]
we don't support Python 3.9, I'd recommend installing python via brew on macOS `brew install python` (or `brew install python@3.12`)
