### ISSUE TITLE
IntegerAttr cannot be built using value and type using `build`

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#263]
IntegerAttr cannot be built using value and type:

```
>>> int_t = IntegerType.from_width(32)
>>> int_attr = IntegerAttr.build(42, int_t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anton/uni/xdslproject/xdsl/xdsl/irdl.py", line 1226, in <lambda>
    new_fields["build"] = lambda *args: irdl_attr_builder(cls, builders, *args)
  File "/home/anton/uni/xdslproject/xdsl/xdsl/irdl.py", line 1184, in irdl_attr_builder
    res = irdl_attr_try_builder(builder, *args)
  File "/home/anton/uni/xdslproject/xdsl/xdsl/irdl.py", line 1174, in irdl_attr_try_builder
    return builder(*args, *defaults[len(args):])
TypeError: IntegerAttr.from_index_int_value() takes 1 positional argument but 2 were given
>>> int_attr = IntegerAttr.from_
IntegerAttr.from_index_int_value(  IntegerAttr.from_int_and_width(    IntegerAttr.from_params(           
>>> int_attr = IntegerAttr.from_params(42, int_t)
```

The `from_params` exists and is properly annotated as far as I can see though.

**Comment by math-fehr** [comment]
Builder doesn't exist anymore.
