### ISSUE TITLE
backend: (risc-v) `IndexError` when translating a `memref` with non-identity strides

### ISSUE THREAD

**Issue by zero9178** [xdslproject/xdsl#2817]
Given this very stupid kernel:
```mlir
func.func @main$async_dispatch_0_matmul_transpose_b_1x400x161_f64$xdsl_kernel1(%arg0: memref<1x1xf64, strided<[50, 1]>>) {
  %cst = arith.constant 0.000000e+00 : f64
  linalg.generic {indexing_maps = [affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%cst : f64) outs(%arg0 : memref<1x1xf64, strided<[50, 1]>>) {
  ^bb0(%in: f64, %out: f64):
    linalg.yield %in : f64
  }
  return
}
```
When run with `xdsl-opt -p "arith-add-fastmath, convert-linalg-to-memref-stream,test-optimise-memref-stream,test-lower-memref-stream-to-snitch-stream,test-lower-snitch-stream-to-asm" -t riscv-asm` yields the following exception:
```mlir
Traceback (most recent call last):
  File "/home/markus/CLionProjects/Quidditch/xdsl/xdsl/pattern_rewriter.py", line 797, in _process_worklist
    self.pattern.match_and_rewrite(op, rewriter)
  File "/home/markus/CLionProjects/Quidditch/xdsl/xdsl/pattern_rewriter.py", line 581, in match_and_rewrite
    pattern.match_and_rewrite(op, rewriter)
  File "/home/markus/CLionProjects/Quidditch/xdsl/xdsl/pattern_rewriter.py", line 426, in impl
    func(self, op, rewriter)
  File "/home/markus/CLionProjects/Quidditch/xdsl/xdsl/transforms/convert_memref_stream_to_snitch_stream.py", line 124, in match_and_rewrite
    stride_patterns = tuple(
                      ^^^^^^
  File "/home/markus/CLionProjects/Quidditch/xdsl/xdsl/transforms/convert_memref_stream_to_snitch_stream.py", line 133, in <genexpr>
    ).simplified()
      ^^^^^^^^^^^^
  File "/home/markus/CLionProjects/Quidditch/xdsl/xdsl/dialects/snitch_stream.py", line 167, in simplified
    ub0, s0 = tuples[0]
              ~~~~~~^^^

IndexError: Error while applying pattern: tuple index out of range

"builtin.module"() ({
  "riscv.assembly_section"() ({
    "riscv.directive"() {"directive" = ".globl", "value" = "main$async_dispatch_0_matmul_transpose_b_1x400x161_f64$xdsl_kernel1"} : () -> ()
    "riscv.directive"() {"directive" = ".p2align", "value" = "2"} : () -> ()
    "riscv_func.func"() ({
    ^0(%arg0 : !riscv.reg<a0>):
      %0 = "riscv.mv"(%arg0) : (!riscv.reg<a0>) -> !riscv.reg
      %arg0_1 = "builtin.unrealized_conversion_cast"(%0) : (!riscv.reg) -> memref<1x1xf64, strided<[50, 1]>>
      %cst = "riscv.li"() {"immediate" = 0 : i32} : () -> !riscv.reg
      %cst_1 = "riscv.fcvt.d.w"(%cst) : (!riscv.reg) -> !riscv.freg
      %cst_2 = "builtin.unrealized_conversion_cast"(%cst_1) : (!riscv.freg) -> f64
      "memref_stream.streaming_region"(%arg0_1) <{"patterns" = [#memref_stream.stride_pattern<ub = [1, 1], index_map = (d0, d1) -> (d0, d1)>], "operandSegmentSizes" = array<i32: 0, 1>}> ({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------------------------
      | Error while applying pattern: tuple index out of range
      --------------------------------------------------------
      ^1(%1 : !stream.writable<f64>):
        "memref_stream.write"(%cst_2, %1) : (f64, !stream.writable<f64>) -> ()
      }) : (memref<1x1xf64, strided<[50, 1]>>) -> ()
      "riscv_func.return"() : () -> ()
    }) {"sym_name" = "main$async_dispatch_0_matmul_transpose_b_1x400x161_f64$xdsl_kernel1", "function_type" = (!riscv.reg<a0>) -> ()} : () -> ()
  }) {"directive" = ".text"} : () -> ()
}) : () -> ()
```

Tested on 80e5f7263cd58fe448e7ffe2f618323965578efb

**Comment by zero9178** [comment]
Fixed by https://github.com/xdslproject/xdsl/commit/c0cbccce4053428e289186206523a67df9adb89d
