### ISSUE TITLE
Detaching multiple regions from an operation breaks that op

### ISSUE THREAD

**Issue by watermelonwolverine** [xdslproject/xdsl#3478]
```python
op.detach_region(op.non_optional_region)
op.detach_region(op.optional_region1)
op.detach_region(op.optional_region2)
```

raises an exception:
```
Traceback (most recent call last):
  ...
  File "/workspace/.venv/lib/python3.10/site-packages/xdsl/irdl/operations.py", line 1823, in fun
    return get_operand_result_or_region(
  File "/workspace/.venv/lib/python3.10/site-packages/xdsl/irdl/operations.py", line 1455, in get_operand_result_or_region
    return args[begin_arg]
IndexError: tuple index out of range
```

Interesting thing to note is that the exception is not raised while removing it, but seemingly while accessing op.optional_region2.
It seems to me that some internal data structures are not updated during detach_region (?).

**Comment by watermelonwolverine** [comment]
Something like this works:

```python
optional_region1 = op.optional_region1
optional_region2 = op.optional_region2

op.detach_region(op.non_optional_region)
op.detach_region(optional_region1)
op.detach_region(optional_region2)
```

**Comment by superlopuh** [comment]
Indeed, it looks like the IRDL wrapper should take this into account and update the `regionSegmentSizes`

**Comment by superlopuh** [comment]
CC @math-fehr

**Comment by math-fehr** [comment]
Hmm, I'm actually not sure how to deal with that one, because that's fundamental on how operations are actually defined.

That's actually not specific to regions btw, you will also see this for operands or results.
If you have non-optional regions, you will actually get the same problem.

So the problem is, how do you get `op.optional_region2`?
You take the regions at index `[1 + regionSegmentSizes[0], 1 + regionSegmentSizes[0] + regionSegmentSizes[1]`.
This is because accessors to operations expect the operation to verify.
Here, because you detached the first region, everything breaks, because the operation doesn't verify anymore, because
you detached a region that was expected to always be there. So all accessors are completely wrong.

I somehow feel we have the wrong API to detach regions, because as soon as we detach regions, we break
the operation accessors.

**Comment by watermelonwolverine** [comment]
So, if I understood correctly, there are two states an operation can be in: A "verified" state is has after verification in which it should work and "modified", where no guarantees can be made?

Maybe we can embrace this a bit by removing the "detach" functions and adding a "dissolve" function instead that dissolves an operation into its constituent parts which can then be re-used. 

This would be useful during rewriting where you don't need the old op anymore, but you also don't want to clone everything to keep performance up.

Alternatively we could replace a detached region with a "poison" object that keeps the number of regions the same but causes verification to fail. This would allow detaching several individual things from an operation.
